service: stock-increase-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::${aws:accountId}:policy/GetBigHeadMySQLSecretValue

functions:
  stock-increase:
    handler: handler.handler
    name: stock-increase
    events:
      - httpApi: '*'
    environment:
      SECRET_MANAGER_ARN: arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:mysql-connection-K9Z7Ad  
