service: stock-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::${aws:accountId}:policy/ReadStockSQS
functions:
  function1:
    handler: index.handler
    events:
      - sqs:
          arn: arn:aws:sqs:${aws:region}:${aws:accountId}:stock-queue
          batchSize: 10
          maximumBatchingWindow: 10
          functionResponseType: ReportBatchItemFailures