service: sales-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::${aws:accountId}:policy/GetBigHeadMySQLSecretValue
        - arn:aws:iam::${aws:accountId}:policy/PublishStockEmptySNS

functions:
  sales:
    handler: handler.handler
    name: sales
    events:
      - httpApi: '*'
    environment:
      SECRET_MANAGER_ARN: arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:mysql-connection-K9Z7Ad
      TOPIC_ARN: arn:aws:sns:${aws:region}:${aws:accountId}:stock-empty

plugins:
  - serverless-ignore