service: sales-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::057440442371:policy/GetBigHeadMySQLSecretValue
        - arn:aws:iam::057440442371:policy/PublishStockEmptySNS

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
    environment:
      SECRET_MANAGER_ARN: arn:aws:secretsmanager:ap-northeast-2:057440442371:secret:mysql-connection-K9Z7Ad
      TOPIC_ARN: arn:aws:sns:ap-northeast-2:057440442371:stock-empty

plugins:
  - serverless-ignore